baseurl = "http://matteoruina.com/"
title = "matteoruina.com"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Matteo Ruina"

[Author]
    name = "Matteo Ruina"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    github = "https://github.com/maruina"
    linkedin = "https://linkedin.com/in/matteoruina"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/page/about/"
#     weight = 2
